### ISSUE TITLE
Question about thermal comfort

### ISSUE THREAD

**Issue by beegee-tokyo** [ADiea/libDHT#3]
Out of curiosity, I want to learn more about the thermal comfort functions. The reference link http://epb.apogee.net/res/refcomf.asp is no longer working. Can you give me some guidance where to get information about the algorithm you used?
Thank you.

**Comment by ADiea** [comment]
Hi maybe you will find this useful
https://www.azosensors.com/article.aspx?ArticleID=487

**Comment by beegee-tokyo** [comment]
Thanks for the link. It was very helpful to understand the background.
